<?php

namespace Database\Seeders;

use App\Models\Operation;
use Illuminate\Database\Seeder;

class OperationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $operations = [
            ['car_id' => 1, 'ref_operation_id' => 1, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 2, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 3, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 4, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 5, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 6, 'index' => 0.8],
            ['car_id' => 1, 'ref_operation_id' => 7, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 8, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 9, 'index' => 0.8],
            ['car_id' => 1, 'ref_operation_id' => 10, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 11, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 12, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 13, 'index' => 0.8],
            ['car_id' => 1, 'ref_operation_id' => 14, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 15, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 16, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 17, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 18, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 19, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 20, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 21, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 22, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 23, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 24, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 25, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 26, 'index' => 0.2],
            ['car_id' => 1, 'ref_operation_id' => 27, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 28, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 29, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 30, 'index' => 0.2],
            ['car_id' => 1, 'ref_operation_id' => 31, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 32, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 33, 'index' => 0.3],
            ['car_id' => 1, 'ref_operation_id' => 34, 'index' => 0.2],
            ['car_id' => 1, 'ref_operation_id' => 35, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 36, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 37, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 38, 'index' => 0.5],
            ['car_id' => 1, 'ref_operation_id' => 39, 'index' => 0.7],
            ['car_id' => 1, 'ref_operation_id' => 40, 'index' => 0.7],
            ['car_id' => 1, 'ref_operation_id' => 41, 'index' => 3],
            ['car_id' => 1, 'ref_operation_id' => 42, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 43, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 44, 'index' => 3],
            ['car_id' => 1, 'ref_operation_id' => 45, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 46, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 47, 'index' => 4],
            ['car_id' => 1, 'ref_operation_id' => 48, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 49, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 50, 'index' => 4],
            ['car_id' => 1, 'ref_operation_id' => 51, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 52, 'index' => 1],
            ['car_id' => 1, 'ref_operation_id' => 53, 'index' => 5],
            ['car_id' => 1, 'ref_operation_id' => 54, 'index' => 4],
            ['car_id' => 1, 'ref_operation_id' => 55, 'index' => 1.5],
            ['car_id' => 1, 'ref_operation_id' => 56, 'index' => 1.5],
            ['car_id' => 1, 'ref_operation_id' => 57, 'index' => 30],
            ['car_id' => 1, 'ref_operation_id' => 58, 'index' => 30],
            ['car_id' => 1, 'ref_operation_id' => 59, 'index' => 30],
            ['car_id' => 2, 'ref_operation_id' => 1, 'index' => 0.6],
            ['car_id' => 2, 'ref_operation_id' => 2, 'index' => 0.6],
            ['car_id' => 2, 'ref_operation_id' => 3, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 4, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 5, 'index' => 0.6],
            ['car_id' => 2, 'ref_operation_id' => 6, 'index' => 0.9],
            ['car_id' => 2, 'ref_operation_id' => 7, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 8, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 9, 'index' => 0.8],
            ['car_id' => 2, 'ref_operation_id' => 10, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 11, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 12, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 13, 'index' => 0.8],
            ['car_id' => 2, 'ref_operation_id' => 14, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 15, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 16, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 17, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 18, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 19, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 20, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 21, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 22, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 23, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 24, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 25, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 26, 'index' => 0.3],
            ['car_id' => 2, 'ref_operation_id' => 27, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 28, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 29, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 30, 'index' => 0.3],
            ['car_id' => 2, 'ref_operation_id' => 31, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 32, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 33, 'index' => 0.3],
            ['car_id' => 2, 'ref_operation_id' => 34, 'index' => 0.2],
            ['car_id' => 2, 'ref_operation_id' => 35, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 36, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 37, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 38, 'index' => 0.5],
            ['car_id' => 2, 'ref_operation_id' => 39, 'index' => 0.7],
            ['car_id' => 2, 'ref_operation_id' => 40, 'index' => 0.7],
            ['car_id' => 2, 'ref_operation_id' => 41, 'index' => 3.1],
            ['car_id' => 2, 'ref_operation_id' => 42, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 43, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 44, 'index' => 3.1],
            ['car_id' => 2, 'ref_operation_id' => 45, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 46, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 47, 'index' => 4],
            ['car_id' => 2, 'ref_operation_id' => 48, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 49, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 50, 'index' => 4],
            ['car_id' => 2, 'ref_operation_id' => 51, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 52, 'index' => 1],
            ['car_id' => 2, 'ref_operation_id' => 53, 'index' => 5],
            ['car_id' => 2, 'ref_operation_id' => 54, 'index' => 4],
            ['car_id' => 2, 'ref_operation_id' => 55, 'index' => 1.5],
            ['car_id' => 2, 'ref_operation_id' => 56, 'index' => 1.5],
            ['car_id' => 2, 'ref_operation_id' => 57, 'index' => 35],
            ['car_id' => 2, 'ref_operation_id' => 58, 'index' => 35],
            ['car_id' => 2, 'ref_operation_id' => 59, 'index' => 35],
            ['car_id' => 3, 'ref_operation_id' => 1, 'index' => 0.6],
            ['car_id' => 3, 'ref_operation_id' => 2, 'index' => 0.6],
            ['car_id' => 3, 'ref_operation_id' => 3, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 4, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 5, 'index' => 0.6],
            ['car_id' => 3, 'ref_operation_id' => 6, 'index' => 0.9],
            ['car_id' => 3, 'ref_operation_id' => 7, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 8, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 9, 'index' => 0.8],
            ['car_id' => 3, 'ref_operation_id' => 10, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 11, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 12, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 13, 'index' => 0.8],
            ['car_id' => 3, 'ref_operation_id' => 14, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 15, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 16, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 17, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 18, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 19, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 20, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 21, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 22, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 23, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 24, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 25, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 26, 'index' => 0.3],
            ['car_id' => 3, 'ref_operation_id' => 27, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 28, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 29, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 30, 'index' => 0.3],
            ['car_id' => 3, 'ref_operation_id' => 31, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 32, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 33, 'index' => 0.3],
            ['car_id' => 3, 'ref_operation_id' => 34, 'index' => 0.2],
            ['car_id' => 3, 'ref_operation_id' => 35, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 36, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 37, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 38, 'index' => 0.5],
            ['car_id' => 3, 'ref_operation_id' => 39, 'index' => 0.7],
            ['car_id' => 3, 'ref_operation_id' => 40, 'index' => 0.7],
            ['car_id' => 3, 'ref_operation_id' => 41, 'index' => 3.1],
            ['car_id' => 3, 'ref_operation_id' => 42, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 43, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 44, 'index' => 3.1],
            ['car_id' => 3, 'ref_operation_id' => 45, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 46, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 47, 'index' => 4],
            ['car_id' => 3, 'ref_operation_id' => 48, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 49, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 50, 'index' => 4],
            ['car_id' => 3, 'ref_operation_id' => 51, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 52, 'index' => 1],
            ['car_id' => 3, 'ref_operation_id' => 53, 'index' => 5],
            ['car_id' => 3, 'ref_operation_id' => 54, 'index' => 4],
            ['car_id' => 3, 'ref_operation_id' => 55, 'index' => 1.5],
            ['car_id' => 3, 'ref_operation_id' => 56, 'index' => 1.5],
            ['car_id' => 3, 'ref_operation_id' => 57, 'index' => 30],
            ['car_id' => 3, 'ref_operation_id' => 58, 'index' => 30],
            ['car_id' => 3, 'ref_operation_id' => 59, 'index' => 30],
            ['car_id' => 1, 'ref_operation_id' => 60, 'index' => 1],


        ];
        foreach ($operations as $operation) {
            Operation::query()->create($operation);
        }
    }
}
